### ISSUE TITLE
Nightly build error.

### ISSUE THREAD

**Issue by scania123** [GloriousEggroll/PhantomBot#189]
I get this when opening the music player. I think its someting in the core. 

javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
        at sun.security.ssl.EngineInputRecord.bytesInCompletePacket(Unknown Source)
        at sun.security.ssl.SSLEngineImpl.readNetRecord(Unknown Source)
        at sun.security.ssl.SSLEngineImpl.unwrap(Unknown Source)
        at javax.net.ssl.SSLEngine.unwrap(Unknown Source)
        at org.java_websocket.SSLSocketChannel2.unwrap(SSLSocketChannel2.java:111)
        at org.java_websocket.SSLSocketChannel2.processHandshake(SSLSocketChannel2.java:91)
        at org.java_websocket.SSLSocketChannel2.<init>(SSLSocketChannel2.java:67)
        at org.java_websocket.server.DefaultSSLWebSocketServerFactory.wrapChannel(DefaultSSLWebSocketServerFactory.java:38)
        at org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:314)
        at java.lang.Thread.run(Unknown Source)

Also "!songrequest 0nlJuwO0GDs#t=15" crashes the bot. (http://phantombot.net/threads/few-other-issues-with-the-bot.1082/)

**Comment by SimeonFr** [comment]
The SSLException will be fixed by #191
